--enable-zero-copy
--canvas-oop-rasterization
--enable-gpu-rasterization
--ozone-platform=wayland
--disable-gpu-driver-bug-workarounds
--enable-gpu

--use-gl=angle
--use-angle=gl

--enable-features=UseOzonePlatform,WaylandWindowDecorations,AcceleratedVideoEncoder,VaapiIgnoreDriverChecks,UseMultiPlaneFormatForHardwareVideo,CanvasOopRasterization,PlatformHEVCDecoderSupport,VaapiVideoDecodeLinuxGL

--disable-features=Vulkan,VulkanFromANGLE,DefaultANGLEVulkan

--ozone-platform-hint=auto