--enable-zero-copy
--canvas-oop-rasterization
--enable-gpu-rasterization
--ozone-platform=wayland
--disable-gpu-driver-bug-workarounds
--ignore-gpu-blocklist
--enable-gpu
--enable-unsafe-webgpu
--use-gl=angle
--use-angle=gl
--enable-features=UseOzonePlatform,WaylandWindowDecorations,AcceleratedVideoEncoder,VaapiIgnoreDriverChecks,UseMultiPlaneFormatForHardwareVideo,CanvasOopRasterization,PlatformHEVCDecoderSupport,VaapiVideoDecodeLinuxGL
--ozone-platform-hint=auto
--disable-features=UseChromeOSDirectVideoDecode