#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/logger.sh"

log_info "GPU Setup: starting"

PACMAN_FLAGS=(--noconfirm --needed)

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    log_error "Missing required command: $1"
    exit 1
  }
}

gpu_lines() {
  lspci -Dnn 2>/dev/null | grep -Ei 'VGA compatible controller|3D controller|Display controller' || true
}

has_intel_gpu()  { gpu_lines | grep -Eqi 'Intel|\[8086:'; }
has_amd_gpu()    { gpu_lines | grep -Eqi 'AMD|ATI|\[1002:'; }
has_nvidia_gpu() { gpu_lines | grep -Eqi 'NVIDIA|\[10de:'; }

has_intel_arc() {
  gpu_lines | grep -Ei 'Intel|\[8086:' | grep -Eqi 'Arc|DG2|Alchemist|Battlemage'
}

is_legacy_intel_igpu() {
  gpu_lines | grep -Ei 'Intel|\[8086:' | grep -Eqi \
    'Sandy|Ivy|Haswell|3rd Gen|2nd Gen|4th Gen|HD Graphics 2|HD Graphics 3|HD Graphics 4|HD Graphics 2500|HD Graphics 3000|HD Graphics 4000'
}

gpu_count() {
  gpu_lines | grep -c . || true
}

# Return the PCI address of the GPU we want as the system-wide performance GPU.
# This deliberately favors a discrete GPU when an iGPU + dGPU combination is detected.
# Selection order: NVIDIA dGPU -> AMD dGPU -> Intel Arc -> single detected GPU.
preferred_gpu_pci() {
  local lines nvidia amd arc intel count
  lines="$(gpu_lines)"
  count="$(printf '%s\n' "$lines" | grep -c . || true)"

  nvidia="$(printf '%s\n' "$lines" | grep -Ei 'NVIDIA|\[10de:' | awk '{print $1}' | head -n1 || true)"
  amd="$(printf '%s\n' "$lines" | grep -Ei 'AMD|ATI|\[1002:' | awk '{print $1}' | head -n1 || true)"
  arc="$(printf '%s\n' "$lines" | grep -Ei 'Intel|\[8086:' | grep -Ei 'Arc|DG2|Alchemist|Battlemage' | awk '{print $1}' | head -n1 || true)"
  intel="$(printf '%s\n' "$lines" | grep -Ei 'Intel|\[8086:' | awk '{print $1}' | head -n1 || true)"

  if (( count > 1 )); then
    [[ -n "$nvidia" ]] && { echo "$nvidia"; return 0; }

    # Intel iGPU + AMD GPU is unambiguous: prefer AMD.
    if [[ -n "$amd" && -n "$intel" ]]; then
      echo "$amd"
      return 0
    fi

    [[ -n "$amd" ]] && { echo "$amd"; return 0; }
    [[ -n "$arc" ]] && { echo "$arc"; return 0; }
  fi

  printf '%s\n' "$lines" | awk 'NR==1 {print $1}'
}

pci_vendor_id() {
  local pci="$1"
  cat "/sys/bus/pci/devices/$pci/vendor" 2>/dev/null | sed 's/^0x//' || true
}

pci_device_id() {
  local pci="$1"
  cat "/sys/bus/pci/devices/$pci/device" 2>/dev/null | sed 's/^0x//' || true
}

render_node_for_pci() {
  local pci="$1" node
  for node in "/sys/bus/pci/devices/$pci/drm/"renderD*; do
    [[ -e "$node" ]] || continue
    echo "/dev/dri/$(basename "$node")"
    return 0
  done
  return 1
}

install_common_stack() {
  log_info "Installing common GPU userspace tools"
  paru -S \
    mesa lib32-mesa \
    libva libva-utils \
    mesa-utils vulkan-tools \
    opencl-mesa \
    egl-wayland egl-gbm \
    vulkan-mesa-implicit-layers lib32-vulkan-mesa-implicit-layers \
    "${PACMAN_FLAGS[@]}"
}

install_intel_stack() {
  log_info "Installing Intel GPU stack"
  paru -S \
    vulkan-intel lib32-vulkan-intel \
    intel-media-driver \
    intel-gpu-tools \
    libvdpau-va-gl \
    "${PACMAN_FLAGS[@]}"

  if is_legacy_intel_igpu; then
    log_info "Legacy Intel iGPU detected; installing i965 VA-API driver"
    paru -S libva-intel-driver lib32-libva-intel-driver "${PACMAN_FLAGS[@]}"
  fi

  paru -S intel-compute-runtime "${PACMAN_FLAGS[@]}" || true
}

install_amd_stack() {
  log_info "Installing AMD GPU stack"
  paru -S \
    vulkan-radeon lib32-vulkan-radeon \
    amdgpu_top rocm-smi-lib amdsmi \
    amf-headers \
    "${PACMAN_FLAGS[@]}"
}

kernel_headers_pkg_for_running_kernel() {
  pacman -Qoq "/usr/lib/modules/$(uname -r)/build" 2>/dev/null | head -n1 || true
}

install_nvidia_stack() {
  local driver_pkg="nvidia-open-dkms" headers_pkg
  headers_pkg="$(kernel_headers_pkg_for_running_kernel)"

  if [[ -n "$headers_pkg" ]]; then
    log_info "Detected kernel headers package: $headers_pkg"
    paru -S "$headers_pkg" "${PACMAN_FLAGS[@]}"
  else
    log_warn "Could not detect headers for the running kernel"
  fi

  log_info "Installing NVIDIA GPU stack"
  paru -S \
    "$driver_pkg" nvidia-utils lib32-nvidia-utils nvidia-settings \
    libva-nvidia-driver \
    "${PACMAN_FLAGS[@]}"
}

write_nvidia_modprobe_conf() {
  local conf="/etc/modprobe.d/nvidia.conf"
  log_info "Writing $conf"
  sudo tee "$conf" >/dev/null <<'CONF'
# Generated by dotfiles installer
options nvidia_drm modeset=1
options nvidia NVreg_PreserveVideoMemoryAllocations=1
CONF
}

ensure_nvidia_mkinitcpio_modules() {
  local file="/etc/mkinitcpio.conf"
  local want_modules=(nvidia nvidia_modeset nvidia_uvm nvidia_drm)
  local current joined
  local -a parts=() new_list=()
  local -A seen=()

  has_intel_gpu && want_modules=(i915 "${want_modules[@]}")

  [[ -f "$file" ]] || { log_error "Missing $file"; return 1; }

  current="$(sudo sed -nE 's/^MODULES=\((.*)\).*/\1/p' "$file" | head -n1 || true)"
  if [[ -n "$current" ]]; then
    # MODULES is space-separated; temporarily use normal shell word splitting.
    IFS=' ' read -r -a parts <<< "$current"
    for m in "${parts[@]}"; do
      seen["$m"]=1
      new_list+=("$m")
    done
  fi

  for m in "${want_modules[@]}"; do
    if [[ -z "${seen[$m]:-}" ]]; then
      new_list+=("$m")
      seen["$m"]=1
    fi
  done

  joined="$(printf '%s ' "${new_list[@]}")"
  joined="${joined% }"

  if sudo grep -qE '^MODULES=\(' "$file"; then
    sudo sed -i -E "s|^MODULES=\(.*\)|MODULES=($joined)|" "$file"
  else
    sudo sed -i "1iMODULES=($joined)" "$file"
  fi

  sudo mkinitcpio -P
}

ensure_nvidia_kernel_param() {
  local param="nvidia.NVreg_PreserveVideoMemoryAllocations=1"

  if [[ -f /etc/default/grub ]] && command -v grub-mkconfig >/dev/null 2>&1; then
    if grep -qE '^\s*GRUB_CMDLINE_LINUX_DEFAULT=' /etc/default/grub; then
      if ! grep -q "$param" /etc/default/grub; then
        sudo sed -i -E "s|^(GRUB_CMDLINE_LINUX_DEFAULT=\")([^\"]*)\"|\\1\\2 $param\"|" /etc/default/grub
      fi
      sudo grub-mkconfig -o /boot/grub/grub.cfg
      return 0
    fi
  fi

  if [[ -d /boot/loader/entries ]]; then
    local entry
    shopt -s nullglob
    for entry in /boot/loader/entries/*.conf; do
      grep -qE '^\s*options\s+' "$entry" || continue
      grep -q "$param" "$entry" && continue
      sudo sed -i -E "s|^(options\s+.*)$|\\1 $param|" "$entry"
    done
    shopt -u nullglob
    return 0
  fi

  log_warn "Could not automatically add $param to the bootloader"
}

enable_nvidia_services() {
  local u
  for u in nvidia-suspend.service nvidia-hibernate.service nvidia-resume.service; do
    systemctl list-unit-files "$u" >/dev/null 2>&1 && sudo systemctl enable "$u" || true
  done

  for u in nvidia-persistenced.service nvidia-powerd.service; do
    systemctl list-unit-files "$u" >/dev/null 2>&1 && sudo systemctl enable --now "$u" || true
  done
}

write_gpu_preference() {
  local pci="$1" vendor device render dri_prime env_dir env_file
  vendor="$(pci_vendor_id "$pci")"
  device="$(pci_device_id "$pci")"
  render="$(render_node_for_pci "$pci" || true)"
  dri_prime="pci-${pci//[:.]/_}"
  env_dir="${XDG_CONFIG_HOME:-$HOME/.config}/environment.d"
  env_file="$env_dir/90-gpu-preference.conf"

  mkdir -p "$env_dir"

  log_info "Preferring GPU $pci (vendor=$vendor, device=$device${render:+, render=$render})"

  {
    echo "# Generated by install_gpu_drivers.sh"
    echo "# Prefer the detected discrete/performance GPU globally."

    case "$vendor" in
      1002)
        # AMD is the preferred GPU. Keep Intel userspace installed for an iGPU,
        # but never let libva auto-select iHD for the AMD render node.
        echo "DRI_PRIME=$dri_prime"
        echo "LIBVA_DRIVER_NAME=radeonsi"
        ;;
      10de)
        echo "__NV_PRIME_RENDER_OFFLOAD=1"
        echo "__GLX_VENDOR_LIBRARY_NAME=nvidia"
        echo "__VK_LAYER_NV_optimus=NVIDIA_only"
        echo "LIBVA_DRIVER_NAME=nvidia"
        echo "NVD_BACKEND=direct"
        echo "MOZ_DISABLE_RDD_SANDBOX=1"
        ;;
      8086)
        # Only make Intel the global media/render preference when either:
        #   * an Intel Arc dGPU was selected, or
        #   * Intel is the only GPU vendor in the machine.
        # An Intel iGPU alongside AMD/NVIDIA must never set global Intel prefs.
        if has_intel_arc || { ! has_amd_gpu && ! has_nvidia_gpu; }; then
          echo "DRI_PRIME=$dri_prime"
          echo "LIBVA_DRIVER_NAME=iHD"
        fi
        ;;
    esac

    # Firefox can select the exact DRM render device on multi-GPU systems.
    [[ -n "$render" ]] && echo "MOZ_DRM_DEVICE=$render"
  } > "$env_file"

  log_ok "GPU preference written to $env_file"
}

show_detection() {
  local count
  count="$(gpu_count)"
  log_info "Detected $count display GPU(s):"
  while IFS= read -r line; do
    [[ -n "$line" ]] && log_info "  $line"
  done < <(gpu_lines)

  if (( count > 1 )); then
    log_info "Hybrid/multi-GPU system detected; all detected vendor drivers will be installed"
  fi
}

main() {
  require_cmd lspci
  require_cmd paru
  sudo -v

  show_detection

  if (( $(gpu_count) == 0 )); then
    log_warn "No supported display GPU detected; skipping GPU setup"
    exit 0
  fi

  install_common_stack

  has_intel_gpu  && install_intel_stack
  has_amd_gpu    && install_amd_stack

  if has_nvidia_gpu; then
    install_nvidia_stack
    write_nvidia_modprobe_conf
    ensure_nvidia_mkinitcpio_modules
    ensure_nvidia_kernel_param
    enable_nvidia_services
  fi

  local preferred
  preferred="$(preferred_gpu_pci)"
  if [[ -n "$preferred" ]]; then
    write_gpu_preference "$preferred"
  else
    log_warn "Could not determine a preferred GPU"
  fi

  log_ok "GPU Setup: done"
  log_info "Log out and back in (or reboot) so environment.d GPU preferences are applied"
  log_info "Verify rendering with: glxinfo -B"
  log_info "Verify VA-API with: vainfo"
  log_info "Verify Vulkan with: vulkaninfo --summary"
}

main "$@"
