#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/logger.sh"

log_info "NVIDIA Setup: starting"

PACMAN_FLAGS=(--noconfirm --needed)

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    log_error "Missing required command: $1"
    exit 1
  }
}

has_nvidia_gpu() {
  if command -v lspci >/dev/null 2>&1; then
    lspci -nn | grep -Eqi 'VGA|3D|Display' | grep -qi nvidia && return 0
  fi
  lsmod 2>/dev/null | grep -q '^nvidia' && return 0
  return 1
}

has_intel_igpu() {
  command -v lspci >/dev/null 2>&1 || return 1
  lspci -nn | grep -Eqi 'VGA|3D|Display' | grep -qi 'intel' && return 0
  return 1
}

detect_driver_flavor() {
  echo "nvidia-open-dkms"
}

kernel_headers_pkg_for_running_kernel() {
  # Best-effort: find which package owns the kernel build directory
  local krel
  krel="$(uname -r)"
  pacman -Qoq "/usr/lib/modules/${krel}/build" 2>/dev/null | head -n1 || true
}

install_nvidia_stack() {
  require_cmd paru
  sudo -v

  local driver_pkg headers_pkg
  driver_pkg="$(detect_driver_flavor)"
  headers_pkg="$(kernel_headers_pkg_for_running_kernel)"

  log_info "Installing NVIDIA driver package: $driver_pkg"
  if [[ -n "$headers_pkg" ]]; then
    log_info "Detected kernel headers package for running kernel: $headers_pkg"
    paru -S "$headers_pkg" "${PACMAN_FLAGS[@]}"
  else
    log_warn "Could not detect headers package for running kernel. Ensure your kernel headers are installed (e.g. linux-headers / linux-lts-headers / linux-zen-headers)."
  fi

  # Hyprland wiki recommends DKMS for Arch in general; also wants nvidia-utils + egl-wayland. :contentReference[oaicite:1]{index=1}
  paru -S \
    "$driver_pkg" nvidia-utils nvidia-settings egl-wayland \
    libva-nvidia-driver lib32-nvidia-utils \
    "${PACMAN_FLAGS[@]}"
}

write_modprobe_conf() {
  sudo -v
  local conf="/etc/modprobe.d/nvidia.conf"

  log_info "Writing $conf"
  sudo install -Dm644 /dev/null "$conf"

  # modeset=1 per Hyprland wiki. :contentReference[oaicite:2]{index=2}
  # PreserveVideoMemoryAllocations requested; Hyprland wiki suggests kernel param, but module option is equivalent in practice.
  sudo tee "$conf" >/dev/null <<'EOF'
# Generated by dotfiles installer
# Enable DRM KMS (required for Wayland compositors like Hyprland)
options nvidia_drm modeset=1

# Preserve VRAM allocations across suspend/hibernate (also can be passed as kernel parameter)
options nvidia NVreg_PreserveVideoMemoryAllocations=1
EOF
}

ensure_mkinitcpio_modules() {
  sudo -v
  local file="/etc/mkinitcpio.conf"
  local want_modules=("nvidia" "nvidia_modeset" "nvidia_uvm" "nvidia_drm")

  # On Intel+NVIDIA hybrid, load i915 before NVIDIA modules to avoid post-boot stalls (Hyprland wiki). :contentReference[oaicite:3]{index=3}
  if has_intel_igpu; then
    want_modules=("i915" "${want_modules[@]}")
  fi

  log_info "Ensuring NVIDIA modules in $file (MODULES array)"
  if ! sudo test -f "$file"; then
    log_error "Missing $file"
    exit 1
  fi

  # Read current MODULES=(...)
  local current
  current="$(sudo sed -nE 's/^MODULES=\((.*)\).*/\1/p' "$file" | head -n1 || true)"

  # Build new list preserving existing order, then append missing in desired order.
  # Split existing on spaces.
  declare -A seen=()
  new_list=()

  if [[ -n "$current" ]]; then
    # shellcheck disable=SC2206
    parts=($current)
    for m in "${parts[@]}"; do
      seen["$m"]=1
      new_list+=("$m")
    done
  fi

  for m in "${want_modules[@]}"; do
    if [[ -z "${seen[$m]:-}" ]]; then
      new_list+=("$m")
      seen["$m"]=1
    fi
  done

  # Write back
  local joined
  joined="$(printf '%s ' "${new_list[@]}")"
  joined="${joined%% }"

  if sudo grep -qE '^MODULES=\(' "$file"; then
    sudo sed -i -E "s|^MODULES=\(.*\)|MODULES=($joined)|" "$file"
  else
    log_warn "No MODULES=() line found in $file; prepending one."
    sudo sed -i "1iMODULES=($joined)\n" "$file"
  fi

  log_info "Rebuilding initramfs: mkinitcpio -P"
  sudo mkinitcpio -P
}

ensure_kernel_param_preserve_vram() {
  # Best-effort: add kernel parameter nvidia.NVreg_PreserveVideoMemoryAllocations=1
  # (Hyprland wiki suggests adding it; we do it if we can detect GRUB or systemd-boot). :contentReference[oaicite:4]{index=4}
  sudo -v
  local param="nvidia.NVreg_PreserveVideoMemoryAllocations=1"

  # GRUB
  if [[ -f /etc/default/grub ]] && command -v grub-mkconfig >/dev/null 2>&1; then
    if grep -qE '^\s*GRUB_CMDLINE_LINUX_DEFAULT=' /etc/default/grub; then
      if grep -q "$param" /etc/default/grub; then
        log_info "Kernel param already present in /etc/default/grub"
      else
        log_info "Adding kernel param to /etc/default/grub"
        sudo sed -i -E "s|^(GRUB_CMDLINE_LINUX_DEFAULT=\")([^\"]*)\"|\\1\\2 $param\"|" /etc/default/grub
      fi
      log_info "Regenerating GRUB config"
      if [[ -f /boot/grub/grub.cfg ]]; then
        sudo grub-mkconfig -o /boot/grub/grub.cfg
      else
        sudo grub-mkconfig -o /boot/grub/grub.cfg
      fi
      return 0
    fi
  fi

  # systemd-boot
  if [[ -d /boot/loader/entries ]]; then
    local changed=0
    shopt -s nullglob
    for entry in /boot/loader/entries/*.conf; do
      if grep -qE '^\s*options\s+' "$entry"; then
        if grep -q "$param" "$entry"; then
          continue
        fi
        log_info "Adding kernel param to systemd-boot entry: $entry"
        sudo sed -i -E "s|^(options\s+.*)$|\\1 $param|" "$entry"
        changed=1
      fi
    done
    shopt -u nullglob

    if [[ $changed -eq 1 ]]; then
      log_ok "Updated systemd-boot entries with $param"
      return 0
    fi
  fi

  log_warn "Could not auto-add kernel parameter ($param). Add it manually in your bootloader if needed."
}

enable_nvidia_services() {
  sudo -v
  # Hyprland wiki mentions enabling these sleep services. :contentReference[oaicite:5]{index=5}
  local units=(
    nvidia-suspend.service
    nvidia-hibernate.service
    nvidia-resume.service
  )

  for u in "${units[@]}"; do
    if systemctl list-unit-files | grep -q "^$u"; then
      log_info "Enabling $u"
      sudo systemctl enable "$u"
    else
      log_warn "Service not found (skipping): $u"
    fi
  done

  # Nice-to-have (only if present)
  for u in nvidia-persistenced.service nvidia-powerd.service; do
    if systemctl list-unit-files | grep -q "^$u"; then
      log_info "Enabling $u"
      sudo systemctl enable --now "$u" || sudo systemctl enable "$u" || true
    fi
  done
}

main() {
  if ! has_nvidia_gpu; then
    log_info "No NVIDIA GPU detected; skipping NVIDIA setup"
    log_ok "NVIDIA Setup: done (skipped)"
    exit 0
  fi

  log_info "NVIDIA GPU detected; applying Hyprland-oriented NVIDIA setup"

  install_nvidia_stack
  write_modprobe_conf
  ensure_mkinitcpio_modules
  ensure_kernel_param_preserve_vram
  enable_nvidia_services

  log_ok "NVIDIA Setup: done"
  log_info "Reboot recommended to apply kernel/module changes."
}

main
